Repository emanuelleGued/harpyja, pull requests merged in 2025-04, with the labels that each got.

#1 Criando classes no service
  src/main/java/com/project/harpyja/controller/UserController.java
  src/main/java/com/project/harpyja/repository/UserRepository.java
  src/main/java/com/project/harpyja/repository/UserWithProjectKey.java
  src/main/java/com/project/harpyja/service/UserService.java
  src/main/java/com/project/harpyja/service/UserServiceImpl.java
Labels: feature, easy

#2 Algumas adicoes reformas
  src/main/java/com/project/harpyja/config/SecurityConfig.java
  src/main/java/com/project/harpyja/controller/UserController.java
  src/main/java/com/project/harpyja/service/JwtUtil.java
  src/main/java/com/project/harpyja/service/UserService.java
  src/main/java/com/project/harpyja/service/UserServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement, feature, easy

#6 Add onboarding feature
  src/main/java/com/project/harpyja/controller/OnboardingController.java
  src/main/java/com/project/harpyja/dto/request/AccountRegisterRequest.java
  src/main/java/com/project/harpyja/dto/request/IntentionAccountRegisterRequest.java
  src/main/java/com/project/harpyja/dto/response/AccountRegisterResponse.java
  src/main/java/com/project/harpyja/model/enums/OrganizationStatus.java
  src/main/java/com/project/harpyja/repository/AddressRepository.java
  src/main/java/com/project/harpyja/repository/AddressRepositoryImpl.java
  src/main/java/com/project/harpyja/repository/OrganizationRepository.java
  src/main/java/com/project/harpyja/repository/OrganizationRepositoryImpl.java
  src/main/java/com/project/harpyja/repository/UserOrganizationRepository.java
  src/main/java/com/project/harpyja/repository/UserOrganizationRepositoryImpl.java
  src/main/java/com/project/harpyja/repository/UserRepository.java
  src/main/java/com/project/harpyja/service/AddressService.java
  src/main/java/com/project/harpyja/service/AddressServiceImpl.java
  src/main/java/com/project/harpyja/service/OnboardingService.java
  src/main/java/com/project/harpyja/service/OnboardingServiceImpl.java
  src/main/java/com/project/harpyja/service/OrganizationService.java
  src/main/java/com/project/harpyja/service/OrganizationServiceImpl.java
  src/main/java/com/project/harpyja/service/UserOrganizationService.java
  src/main/java/com/project/harpyja/service/UserOrganizationServiceImpl.java
  src/main/java/com/project/harpyja/service/UserService.java
  src/main/java/com/project/harpyja/service/UserServiceImpl.java
Labels: feature
